services:
  server:
    image: sfdeloach/event-hub-server-dev:latest
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: server-dev
    restart: unless-stopped
    ports:
      - "7331:7331"
    volumes:
      - ./server:/app # Updated to match WORKDIR in Dockerfile.dev
