services:
  database:
    image: postgres:18-alpine
    container_name: database-prod
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata-prod:/var/lib/postgresql
    networks:
      - app-network-prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    image: sfdeloach/event-hub-server-prod:0.0.0
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: server-prod
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SSLMODE=${POSTGRES_SSLMODE}
    ports:
      - "80:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-network-prod

networks:
  app-network-prod:
    driver: bridge

volumes:
  pgdata-prod:
